- arguments: [--cpp-define=HLINT, --cpp-ansi]

- ignore: {name: Reduce duplication}
- ignore: {name: Redundant lambda}
- ignore: {name: Use >=>}
- ignore: {name: Use const}
- ignore: {name: Eta reduce}
- ignore: {name: Avoid lambda}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Avoid lambda using `infix`}
